data_cfg:
  dataset_name: MD17
  root: data/MD17
  name: benzene
  train_size: 1000
  valid_size: 1000
  seed: 42
  shuffle: False

network_cfg:
  name: schnet
  # hidden_channels: 128
  hidden_channels: 256
  num_filters: 128
  # cutoff: 10.0
  cutoff: 5.0
  energy_and_force: true
  num_interactions: 3
  num_gaussians: 50

train_cfg:
  project_name: MoleculeDynamics-Expert-Trajectory
  epochs: 3000
  batch_size: 1
  vt_batch_size: 128
  optimizer_name: Adam
  weight_decay: 0
  val_step: 1
  test_step: 30000000
  save_step: 1
  early_epoch: 3000
  early_save_iters: 250
  lr: 1.0e-4
  scheduler_name: ExpDecayLR
  lr_decay_step_size: 20000
  lr_decay_factor: 0.95
  energy_and_force: true
  p: 100
  loss_func: 'l2'