distill_cfg:
  project_name: 'MoleculeDynamics-Data-Distill'
  algorithm: 'mtt'
  num_iteration: 5000
  num_step_per_iteration: 10
  all_distill_data_per_iteration: True
  expert_network: 'SchNet'
  expert_trajectory_dir: '.ckpt/expert_trajectory/schnet/benzene'
  max_start_epoch: 500
  num_expert_epoch: 3
  eval_step: 200
  eval_network_pool: ['SchNet']
  eval_train_epoch: 1000
  eval_batch_size: 1
  eval_scheduler_name: "ExpDecayLR"
  eval_vt_batch_size: 256
  eval_lr_decay_factor: 0.95
  eval_lr_decay_step_size: 100000
  save_step: 100
  distill_rate: 0.6
  distill_batch: 4
  # distill_lr_assistant_net: None
  # distill_lr_lr: None
  enable_assistant_net: False
  distill_base_lr: 3.0e-10
  distill_energy_and_force: True
  distill_lr_pos: 1.0e-2
  lr_requires_grad: False
  pos_requires_grad: True
  energy_requires_grad: False
  force_requires_grad: False
  max_grad_norm_clip: 1.0
  # reinfer_energy_and_force: False