distill_cfg:
  project_name: 'MoleculeDynamics-Data-Distill'
  algorithm: 'mtt'
  num_iteration: 5000
  num_step_per_iteration: 20
  all_distill_data_per_iteration: True
  num_clusters: 500
  enable_assistant_net: True
  expert_network: 'SchNet'
  expert_trajectory_dir: '.ckpt/expert_trajectory/schnet/benzene'
  max_start_epoch: 150
  min_start_epoch: 149
  num_expert_epoch: 1
  eval_step: 2000
  eval_network_pool: ['SchNet']
  eval_train_epoch: 1000
  eval_scheduler_name: "ExpDecayLR"
  eval_vt_batch_size: 256
  eval_lr_decay_factor: 0.95
  eval_lr_decay_step_size: 100000
  save_step: 1000
  distill_rate: 0.6
  distill_batch: 16
  distill_lr_assistant_net: 1.0e-4
  distill_base_lr: 8.0e-10
  distill_energy_and_force: True
  dynamic_optimizer_type: "sgd"
  distill_optimizer_type: "adam"
  distill_lr_pos: 3.0e-2
  lr_requires_grad: False
  pos_requires_grad: False
  energy_requires_grad: False
  force_requires_grad: False
  revise_energy_and_force: False