distill_cfg:
  project_name: 'MoleculeDynamics-Data-Distill'
  algorithm: 'mtt'
  num_iteration: 25
  num_step_per_iteration: 10
  all_distill_data_per_iteration: True
  noise_pos: False
  expert_network: 'SchNet'
  expert_trajectory_dir: '.ckpt/expert_trajectory/schnet/benzene'
  max_start_iter: 20000
  min_start_iter: 0
  num_expert: 2
  eval_step: 5
  eval_network_pool: ['SchNet']
  eval_train_epoch: 20
  eval_vt_batch_size: 128
  eval_scheduler_name: None
  eval_lr_decay_factor: None
  eval_lr_decay_step_size: None
  save_step: 5
  distill_rate: 0.4
  # distill_batch: 16
  distill_batch: 1
  distill_lr_lr: 1.0e-12
  enable_assistant_net: False
  distill_base_lr: 8.0e-10
  distill_energy_and_force: True
  dynamic_optimizer_type: "sgd"
  distill_optimizer_type: "adam"
  lr_requires_grad: True
  pos_requires_grad: True
  distill_lr_pos: 1.0e-3
  energy_requires_grad: True
  distill_lr_energy: 1.0e-3
  force_requires_grad: True
  distill_lr_force: 1.0e-3
  revise_energy_and_force: False
  check_energy_and_force: True