distill_cfg:
  project_name: 'MoleculeDynamics-Data-Distill'
  algorithm: 'mtt'
  num_iteration: 5000
  num_step_per_iteration: 16
  all_distill_data_per_iteration: True
  noise_pos: False
  expert_network: 'SchNet'
  expert_trajectory_dir: '.ckpt/expert_trajectory/schnet/benzene'
  max_start_epoch: 1
  min_start_epoch: 0
  num_expert_epoch: 1
  eval_step: 1000
  eval_network_pool: ['SchNet']
  eval_train_epoch: 1000
  # eval_batch_size: 128
  eval_scheduler_name: "ExpDecayLR"
  eval_vt_batch_size: 128
  eval_lr_decay_factor: 0.95
  eval_lr_decay_step_size: 100000
  save_step: 100
  distill_rate: 0.4
  distill_batch: 4
  # distill_lr_assistant_net: None
  distill_lr_lr: 1.0e-12
  enable_assistant_net: False
  distill_base_lr: 1.0e-9
  distill_energy_and_force: True
  dynamic_optimizer_type: "sgd"
  distill_optimizer_type: "adam"
  lr_requires_grad: True
  pos_requires_grad: True
  distill_lr_pos: 1.0e-3
  energy_requires_grad: True
  distill_lr_energy: 1.0e-3
  force_requires_grad: True
  distill_lr_force: 1.0e-3
  # max_grad_norm_clip: 1.0
  revise_energy_and_force: False
  check_energy_and_force: True